<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="2.765" timestamp="2023-06-23T17:31:28.668420" hostname="IN3330620W1"><testcase classname="" name="test_HomePage" time="0.000"><error message="collection failure">test_HomePage.py:10: in &lt;module&gt;
    class TestHomePage(Baseclass):
test_HomePage.py:31: in TestHomePage
    @pytest.fixture(params=HomePageData.getTestData("Testcase1"))
..\Testdata\HomePageData.py:14: in getTestData
    book = openpyxl.load_workbook("https:\\people.ey.com\\personal\\jeet_chakraborty1_gds_ey_com\\Documents\\Desktop\\TestData.xlsx?web=1")
..\..\..\..\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\reader\excel.py:344: in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
..\..\..\..\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\reader\excel.py:123: in __init__
    self.archive = _validate_archive(fn)
..\..\..\..\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\reader\excel.py:93: in _validate_archive
    raise InvalidFileException(msg)
E   openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support .xlsx?web=1 file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm</error></testcase></testsuite></testsuites>